# Generated by Django 4.0.1 on 2022-01-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_magasin_options_alter_person_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magasin_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='profilmagasin',
            name='magasin',
        ),
        migrations.AlterModelOptions(
            name='magasin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.RemoveField(
            model_name='magasin',
            name='country',
        ),
        migrations.RemoveField(
            model_name='magasin',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='magasin',
            name='name',
        ),
        migrations.RemoveField(
            model_name='magasin',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.RemoveField(
            model_name='person',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='person',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
        migrations.DeleteModel(
            name='ProfilMagasin',
        ),
    ]
