# Generated by Django 4.0.1 on 2022-01-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_produit_profilmagasin_delete_magasin_profile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.RemoveField(
            model_name='person',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='updated_at',
        ),
    ]
