# Generated by Django 4.0.1 on 2022-01-27 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('BJ', 'BENIN'), ('BF', 'BURKINA FASO'), ('CI', "COTE D' IVOIRE"), ('SN', 'SENEGAL'), ('GN', 'GUINEE')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('BJ', 'BENIN'), ('BF', 'BURKINA FASO'), ('CI', "COTE D' IVOIRE"), ('SN', 'SENEGAL'), ('GN', 'GUINEE')], max_length=20)),
                ('age', models.PositiveIntegerField(default=0)),
                ('sex', models.CharField(choices=[('MASCULIN', 'MASCULIN'), ('FEMININ', 'FEMININ')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilMagasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('magasin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='magasin_profil', to='polls.magasin')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('BJ', 'BENIN'), ('BF', 'BURKINA FASO'), ('CI', "COTE D' IVOIRE"), ('SN', 'SENEGAL'), ('GN', 'GUINEE')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='PRODUCT_IMG')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_magasin', to='polls.magasin')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
